Repository xxsvip/shanghai, pull requests merged in 2019-04, with the labels that each got.

#30 原纱入库登记功能的提交
  core/src/main/java/com/tianqiauto/textile/weaving/controller/common/CommonController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/dingdanguanli/DingdanguanliController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/dingdanguanli/HeYueHaoController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/dingdanguanli/HeYueHaoYuanShaController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/yuanshaguanli/YuansharukudengjiController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Heyuehao.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Heyuehao_YuanSha.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Order.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_RuKu.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_RuKu_Shenqing.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_ZhiLiang.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/YuanShaRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/YuanShaRuKuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/YuanShaChuKuService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/YuanShaRuKuService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/common/CommonService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/HeyuehaoService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/OrderService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/YuanShaService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuansharukudengjiServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/util/ModelUtil.java
  core/src/main/resources/static/layuiadmin/modules/common.js
  core/src/main/resources/static/layuiadmin/modules/dingdanguanli/dingdanguanli.js
  core/src/main/resources/static/layuiadmin/modules/yuanshaguanli/yuansharukudengji.js
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/dingdanguanli/dingdanguanli.html
  core/src/main/resources/templates/views/yuanshaguanli/yuansharukudengji.html
Labels: enhancement

#31 Dev shebei
  core/src/main/java/com/tianqiauto/textile/weaving/controller/common/CommonController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/PancunyueController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/shebei/SheBeiController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/shebei/SheBeiParamController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/shebei/SheBeiParamLeiBieController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/zhou/JingZhouController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/zhou/ZhiZhouController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/base/PanCunYue.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Beam_JingZhou.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Beam_ZhiZhou.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/GongXuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/JingZhouRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/PanCunYueRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/SheBeiParamLeiBieRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/SheBeiParamRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/ZhiZhouRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/common/CommonService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jichushezhi/PanCunYueService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jichushezhi/SheBeiParamLeiBieService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jichushezhi/SheBeiParamService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jichushezhi/SheBeiService.java
  core/src/main/resources/static/layuiadmin/modules/common.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/daping/tongzhigonggao.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/juesequanxian/role.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/paiban/gongxupaiban.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/pancunyue.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/shebei/shebeiguanli.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/shebei/shebeiparam.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/shebei/shebeiparamtype.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/zhouguanli/jingzhouguanli.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/zhouguanli/zhizhouguanli.js
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/jichushezhi/jingzhouguanli.html
  core/src/main/resources/templates/views/jichushezhi/pancunyue.html
  core/src/main/resources/templates/views/jichushezhi/shebeiguanli.html
  core/src/main/resources/templates/views/jichushezhi/shebeiparam.html
  core/src/main/resources/templates/views/jichushezhi/shebeiparamtype.html
  core/src/main/resources/templates/views/jichushezhi/zhizhouguanli.html
Labels: enhancement, invalid

#33 新增原纱入库申请确认功能提交
  core/src/main/java/com/tianqiauto/textile/weaving/controller/yuanshaguanli/YuansharukuquerenController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/yuanshaguanli/YuansharukushenqingController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_RuKu.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_RuKu_Shenqing.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuansharukuquerenServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuansharukushenqingServer.java
  core/src/main/resources/static/layuiadmin/modules/yuanshaguanli/yuansharukuqueren.js
  core/src/main/resources/static/layuiadmin/modules/yuanshaguanli/yuansharukushenqing.js
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/yuanshaguanli/yuansharukuqueren.html
Labels: enhancement

#37 Dev chejianzonglan
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/daping/DianShiFangAnController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/daping/TongZhiGongGaoController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/daping/ZhanShiYeMianController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/zhou/JingZhouController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jichushezhi/zhou/ZhiZhouController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/shishishuju/CurJingZhouController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/shishishuju/CurWenShiDuController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/shishishuju/CurZhiZhouController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/TV_DianShiFangAn.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/TV_TongZhiGongGao.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/TV_ZhanShiYeMian.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/WenShiDu.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/DianShiFangAnRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/WenShiDuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/ZhanShiYeMianRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jichushezhi/DianShiFangAnService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jichushezhi/PanCunYueService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/shishishuju/CurDataService.java
  core/src/main/resources/static/css/cjzl.css
  core/src/main/resources/static/js/common/GetUrlParam.js
  core/src/main/resources/static/js/echarts/TIS-echarts.js
  core/src/main/resources/static/js/echarts/echarts.min.js
  core/src/main/resources/static/layuiadmin/modules/common.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/chewei/zhibuchewei.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/daping/dianshifangan.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/daping/tongzhigonggao.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/daping/zhanshiyemian.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/shebei/shebeiguanli.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/chejianzonglan.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/jingzhou.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/wenshidu.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/zhizhou.js
  core/src/main/resources/static/tv/tzgg.html
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/jichushezhi/dianshifangan.html
  core/src/main/resources/templates/views/jichushezhi/tongzhigonggao.html
  core/src/main/resources/templates/views/jichushezhi/zhanshiyemian.html
  core/src/main/resources/templates/views/jichushezhi/zhibuchewei.html
  core/src/main/resources/templates/views/shishishuju/chejianzonglan.html
  core/src/main/resources/templates/views/shishishuju/jingzhou.html
  core/src/main/resources/templates/views/shishishuju/wenshidu.html
  core/src/main/resources/templates/views/shishishuju/zhizhou.html
Labels: enhancement

#35 Dev yuanshachukudengji
  core/src/main/java/com/tianqiauto/textile/weaving/controller/common/CommonController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/yuanshaguanli/YuanshachukudengjiController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Order.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_ChuKu.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_RuKu.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/YuanShaChuKuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/common/CommonService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuanshachukudengjiServer.java
  core/src/main/resources/static/layuiadmin/modules/yuanshaguanli/yuansha.js
  core/src/main/resources/static/layuiadmin/modules/yuanshaguanli/yuanshachukudengji.js
  core/src/main/resources/templates/views/yuanshaguanli/yuansha.html
  core/src/main/resources/templates/views/yuanshaguanli/yuanshachukudengji.html
Labels: enhancement

#38 Dev chejianzonglan
  core/src/main/java/com/tianqiauto/textile/weaving/controller/shishishuju/CurGongXuController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/shishishuju/CurWenShiDuController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Beam_ZhiZhou_Current.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Beam_ZhiZhou_Shift.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Current_BuJi.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/History_WenShiDu.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/HistoryWenShiDuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/shishishuju/CurDataService.java
  core/src/main/resources/static/css/cjzl.css
  core/src/main/resources/static/js/font-awesome/css/font-awesome.css
  core/src/main/resources/static/js/font-awesome/css/font-awesome.min.css
  core/src/main/resources/static/js/font-awesome/fonts/FontAwesome.otf
  core/src/main/resources/static/js/font-awesome/fonts/fontawesome-webfont.eot
  core/src/main/resources/static/js/font-awesome/fonts/fontawesome-webfont.svg
  core/src/main/resources/static/js/font-awesome/fonts/fontawesome-webfont.ttf
  core/src/main/resources/static/js/font-awesome/fonts/fontawesome-webfont.woff
  core/src/main/resources/static/js/font-awesome/fonts/fontawesome-webfont.woff2
  core/src/main/resources/static/layuiadmin/modules/common.js
  core/src/main/resources/static/layuiadmin/modules/jichushezhi/shebei/shebeiguanli.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/buji.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/chejianzonglan.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/jingzhou.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/wenshidu.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/windowpop.js
  core/src/main/resources/static/layuiadmin/modules/shishishuju/zhizhou.js
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/shishishuju/bujizonglan.html
  core/src/main/resources/templates/views/shishishuju/chejianzonglan.html
  core/src/main/resources/templates/views/shishishuju/wenshidu.html
  core/src/test/java/com/tianqiauto/textile/weaving/controller/UserController2Test.java
Labels: enhancement

#39 Bug order2
  core/src/main/java/com/tianqiauto/textile/weaving/controller/dingdanguanli/DingdanguanliController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/dingdanguanli/HeYueHaoController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/yuanshaguanli/YuanshachukushenqingController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Order.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_ChuKu.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/YuanSha_ChuKu_Shenqing.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/OrderRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/YuanShaChuKuShenQingRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/HeYueHaoYuanShaService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/HeyuehaoService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/OrderService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuanshachukushenqingServer.java
  core/src/main/resources/static/layuiadmin/modules/common.js
  core/src/main/resources/static/layuiadmin/modules/dingdanguanli/dingdanguanli.js
  core/src/main/resources/static/layuiadmin/modules/dingdanguanli/heyuehao.js
  core/src/main/resources/static/layuiadmin/modules/yuanshaguanli/yuanshachukushenqing.js
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/dingdanguanli/dingdanguanli.html
  core/src/main/resources/templates/views/dingdanguanli/editOrder.html
  core/src/main/resources/templates/views/yuanshaguanli/yuanshachukushenqing.html
Labels: bug

#41 Dev chengpinrukushenqing
  core/src/main/java/com/tianqiauto/textile/weaving/controller/chengpinguanli/ChengpinrukushenqingController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Chengpin_RuKu.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Chengpin_RuKu_Shenqing.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/ChengpinchukuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/ChengpinchukushenqingRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/ChengpinrukuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/ChengpinrukushenqingRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/DictRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/dao/DictDao.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/chengpinguanli/ChengpinrukushenqingServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/OrderService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuanshachukudengjiServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuanshachukuquerenServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuanshachukushenqingServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuanshakucunchakanServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuansharukudengjiServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuansharukuquerenServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/yuanshaguanli/YuansharukushenqingServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/util/ModelUtil.java
  core/src/main/java/com/tianqiauto/textile/weaving/util/model/ModelUtil.java
  core/src/main/java/com/tianqiauto/textile/weaving/util/model/Param.java
  core/src/main/resources/static/layuiadmin/modules/chengpinguanli/chengpinrukushenqing.js
  core/src/main/resources/static/layuiadmin/modules/common.js
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/chengpinguanli/chengpinrukushenqing.html
Labels: enhancement

#50 Dev bujijihuaxiada
  core/src/main/java/com/tianqiauto/textile/weaving/caiji/PicanolLoomModule/bean/PicanolParam.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/chengpinguanli/ChengpinchukudengjiController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/chengpinguanli/ChengpinchukuquerenController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/chengpinguanli/ChengpinkucunchakanController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/common/CommonController.java
  core/src/main/java/com/tianqiauto/textile/weaving/controller/jihuaguanli/BujijihuaxiadaController.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/JiHua_BuJi.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/Param.java
  core/src/main/java/com/tianqiauto/textile/weaving/model/sys/ZhiXing_BuJi.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/GongXuRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/JihuaBujiRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/repository/ShebeiRepository.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/chengpinguanli/ChengpinchukudengjiServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/chengpinguanli/ChengpinchukuquerenServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/chengpinguanli/ChengpinkucunchakanServer.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/common/CommonService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/dingdanguanli/HeyuehaoService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jichushezhi/UserService.java
  core/src/main/java/com/tianqiauto/textile/weaving/service/jihuaguanli/BujijihuaxiadaServer.java
  core/src/main/resources/static/layuiadmin/modules/chengpinguanli/chengpinchukudengji.js
  core/src/main/resources/static/layuiadmin/modules/chengpinguanli/chengpinchukuqueren.js
  core/src/main/resources/static/layuiadmin/modules/chengpinguanli/chengpinkucunchakan.js
  core/src/main/resources/static/layuiadmin/modules/common.js
  core/src/main/resources/static/layuiadmin/modules/jihuaguanli/bujijihuaxiada.js
  core/src/main/resources/templates/main.html
  core/src/main/resources/templates/views/chengpinguanli/chengpinchukudengji.html
  core/src/main/resources/templates/views/chengpinguanli/chengpinchukuqueren.html
  core/src/main/resources/templates/views/chengpinguanli/chengpinkucunchakan.html
  core/src/main/resources/templates/views/jihuaguanli/bujijihuaxiada.html
Labels: enhancement
